name: checkin
on:
  schedule:
    - cron: "45 1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - env:
          SESS: ${{ secrets.SESS }}
          SIG: ${{ secrets.SIG }}
          SEND: ${{ secrets.SEND }}
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python test_checkin.py
