name: checkin
on:
  schedule:
    - cron: "49 8 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install requests
          python test_checkin.py
